spring:
    application:
        name: bankSystem
    cloud:
        openfeign:
            httpclient:
                disable-ssl-validation: true
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://postgres:5432/banksystemdb
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
        host: rabbitmq
        password: guest
        port: 5672
        username: guest
        listener:
            simple:
                retry:
                    enabled: true
                    initial-interval: 1000
                    max-attempts: 5
                    multiplier: 2.0
                    stateless: true

